
services:
  dreamcar-api:
    container_name: dreamcar-api
    restart: always
    image: node:20.10.0
    ports:
      - 4001:3007
    volumes:
      - ./:/usr/src/dreamcar
    working_dir: /usr/src/dreamcar

    networks:
      - monorepo-network

    # for production
    command: bash -c "rm -rf dist && npm install && npm run build && npm run start:prod"

  dreamcar-batch:
    container_name: dreamcar-batch
    restart: unless-stopped
    image: node:20.10.0
    ports:
      - 4002:3008
    volumes:
      - ./:/usr/src/dreamcar
    working_dir: /usr/src/dreamcar

    networks:
      - monorepo-network

    # for production
    command: bash -c "npm install && npm run build && npm run start:prod:batch"

networks:
  monorepo-network:
    driver: bridge